### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by FFY00** [brettcannon/python-launcher#12]
Hey, would it be possible to start tagging releases so that I can package this for arch? Bonus points if you PGP sign them :wink:

**Comment by brettcannon** [comment]
@FFY00 I plan to start tagging once I hit 1.0, but I'm not _quite_ there yet and ready to have people start packaging this and thus for me to handle bug reports from wide usage 😉 . For instance I still need to see if I can drop the nix dependency for Debian to make it easier for everyone to package.

But yes, once this is ready for wide use I will definitely tag and follow good project management practices. 😁

**Comment by FFY00** [comment]
Ah, okay. I thought it was fine since you have published crates. I'll wait then :smile:.

**Comment by gaborbernat** [comment]
The arch release now is out https://aur.archlinux.org/packages/python-launcher :+1:

**Comment by brettcannon** [comment]
Thanks! I will try to add it to the README this week (see #134 for tracking that)!
