### ISSUE TITLE
Bump serial_test_derive from 0.5.1 to 0.6.0

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/python-launcher#192]
https://github.com/brettcannon/python-launcher/pull/185 shows that the API has changed.

**Comment by carltongibson** [comment]
Was this resolved by 039a6ee41696b8d06efa9080f94bad622fca3c25 and d5f5d17dd85cd0a45f900a88c4bd8f2dfe84984c ? (Thanks)

**Comment by brettcannon** [comment]
@carltongibson it appears so! Thanks for pointing that out!
