### ISSUE TITLE
Distribute binaries

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/python-launcher#22]
https://rust-cli.github.io/book/tutorial/packaging.html

**Comment by brettcannon** [comment]
See if PGO makes a difference: https://doc.rust-lang.org/rustc/profile-guided-optimization.html

**Comment by brettcannon** [comment]
https://www.marcoieni.com/2020/12/rust-makes-cross-compilation-childs-play/

**Comment by brettcannon** [comment]
If a tarball can be constructed to match what `/usr/local` would expect, then people can use the following to extract the tarball and have all the files put in the proper place:
```sh
tar -x --strip-components 1 --exclude LICENSE -f <tarball> -C /usr/local
```

Probably want to create a tarball with:
```sh
tar -c --xz --options xz:compression-level 9 -f <tarball name> <directory>
```

In terms of file structure:
- `LICENSE`
- `bin/py`
- `share/doc/py/LICENSE`
- `share/doc/py/README`
- `share/fish/vendor_completions.d/py.fish`
- `share/man/man1/py.1`

**Comment by brettcannon** [comment]
Should build for (if possible):
1. macOS x64
2. macOS ARM
3. Linux x64
4. Linux ARM
5. Windows x64
6. Windows ARM

Package everything as:
1. `.tar.xz`
2. [`.deb`](https://crates.io/crates/cargo-deb)
3. [`.rpm`](https://crates.io/crates/cargo-rpm)
4. [`.aur`](https://crates.io/crates/cargo-aur)

**Comment by brettcannon** [comment]
Is it worth running `strip` on the binaries? I would assume `cargo build --release` did the right thing. Plus [ripgrep makes it look like a pain](https://github.com/BurntSushi/ripgrep/blob/94e4b8e301302097dad48b292560ce135c4d4926/.github/workflows/release.yml#L164-L175).

**Comment by brettcannon** [comment]
Might be worth looking into installers for:
- Windows
- macOS
- Snap?

**Comment by brettcannon** [comment]
Getting on to Homebrew might be tricky since https://docs.brew.sh/Acceptable-Formulae says self-submitted is frowned upon until a project is popular. Might need to [create my own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) to at least start.

**Comment by pradyunsg** [comment]
If you need someone else to submit this to upstream Homebrew, I'd be happy to!

**Comment by brettcannon** [comment]
https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by brettcannon** [comment]
Based on [rustc support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) and [cross support](https://github.com/rust-embedded/cross#supported-targets), probably will start with building:
1. x86_64-apple-darwin (rustc)
2. aarch64-apple-darwin (hopefully rustc)
3. x86_64-unknown-linux-gnu (rustc)
4. aarch64-unknown-linux-gnu (cross)
4. riscv64gc-unknown-linux-gnu (cross)
3. x86_64-sun-solaris (cross)
4. x86_64-unknown-freebsd (cross)
5. x86_64-unknown-dragonfly (cross)
6. x86_64-unknown-netbsd (cross)

Windows is not a concern as there isn't Windows support yet. Everything else either isn't an OS people run as a dev platform (and thus the Launcher isn't appropriately for), or isn't easily available via cross.

**Comment by brettcannon** [comment]
https://github.com/actions-rs/cargo#cross-compilation
https://github.com/rust-github/template/blob/main/.github/workflows/cd.yml

**Comment by brettcannon** [comment]
Probably should also upload the SHA256 signatures for each file.

**Comment by brettcannon** [comment]
For Homebrew, you need to know things like which path is for completions, man page, etc. Since that info is also necessary to create the tarball appropriately, probably going to need to write out some config data to map repo paths to file purpose.

**Comment by brettcannon** [comment]
To generate the Homebrew formula, there's a [cookbook](https://docs.brew.sh/Formula-Cookbook), [class details](https://rubydoc.brew.sh/Formula.html#fish_completion-instance_method), and can use [ripgrep's formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ripgrep.rb) as guidance.

**Comment by brettcannon** [comment]
Built for Apple Silicon on my x64 Mac:
```
rustup target add aarch64-apple-darwin
cargo build --release --target aarch64-apple-darwin
```

Binary ends up in `target/aarch64-apple-darwin/release/py`.

**Comment by brettcannon** [comment]
Building binaries thanks to https://github.com/brettcannon/python-launcher/commit/020a1717c1227554f6621bdb27c6bc50f5e70536. Still need to do some other release-related steps, but it's a start.

**Comment by brettcannon** [comment]
It seems `tar` on macOS lacks zstd support, but it does have lzma/xz support, so that's probably the best option for compressing tarballs.

**Comment by brettcannon** [comment]
https://github.blog/2021-03-11-scripting-with-github-cli/#using-gh-in-github-actions on how to use `gh` from within Actions.

**Comment by brettcannon** [comment]
https://github.com/brettcannon/python-launcher/commit/0cb42a8c0dc2c9fa60f1fef957172dade29479f5 got the tarball being created.

**Comment by henryiii** [comment]
You should be able to cross compile AS on macOS-10.15, because it has Xcode 12? We are cross compiling wheels with it, anyway.

**Comment by brettcannon** [comment]
@henryiii it's a configuration thing I don't want to bother solving right now since I can cross-compile on my own machine and upload manually. 😄
