### ISSUE TITLE
Local virtualenv not found on WSL2

### ISSUE THREAD

**Issue by lllama** [brettcannon/python-launcher#324]
I've just created a new virtualenv and the launcher is failing to find the interpreter.

I did the following steps:

```bash
> cargo install pylauncher --force
> py -m venv .venv --prompt myrepo
> py -c "import sys; print(sys.version); print(); print(sys.executable)"
3.12.0 (main, Oct  4 2023, 15:31:39) [GCC 11.3.0]

/home/user/.asdf/installs/python/3.12.0/bin/python3.12
```

If I activate the environment then it is used as expected.
Note that I'm using `adsf` to manage my python versions. I have the global interpreter set to 3.12.0.

System details:
WSL2 - Ubuntu 20.04
Bash
Python Launcher for POSIX Version 0.1.1

**Comment by brettcannon** [comment]
You have the wrong repository. You installed https://crates.io/crates/pylauncher , but this repository is for https://crates.io/crates/python-launcher (see https://python-launcher.app/install/#cratesio for the installation command and other installation options).

**Comment by lllama** [comment]
🤦 sorry Brett
