### ISSUE TITLE
NoExecutableFound should write to stderr and return non-zero

### ISSUE THREAD

**Issue by uranusjr** [brettcannon/python-launcher#9]
I was trying to use something like `py -X.Y -c "import sys; print(sys.executable, end='')"` to detect the location of a given interpreter, but the execution result for a non-existant interpreter makes it difficult to handle the output. It would be much easier if the launcher fails in a more script-friendly way.

**Comment by brettcannon** [comment]
Yep, hence why both issues are listed in the [TODO](https://github.com/brettcannon/python-launcher#todo) required to reach an MVP. 😉

**Comment by brettcannon** [comment]
OK, everything that was writing to stdout on failure should now be writing to stderr and there is a non-zero exit code as well. Let me know if it works for you!

**Comment by uranusjr** [comment]
It works flawlessly 🎉
